[2022-12-12 12:49:18,437] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T22:26:00+00:00 [queued]>
[2022-12-12 12:49:19,053] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T22:26:00+00:00 [queued]>
[2022-12-12 12:49:19,054] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:49:19,054] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 12:49:19,054] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:49:20,197] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-28 22:26:00+00:00
[2022-12-12 12:49:20,394] {standard_task_runner.py:52} INFO - Started process 1193 to run task
[2022-12-12 12:49:20,598] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-11-28T22:26:00+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp39fdd6b8', '--error-file', '/tmp/tmpn0z3iybn']
[2022-12-12 12:49:20,728] {standard_task_runner.py:80} INFO - Job 385: Subtask create_table
[2022-12-12 12:49:24,241] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-11-28T22:26:00+00:00 [running]> on host b778137d8ea6
[2022-12-12 12:49:30,344] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T22:26:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T22:26:00+00:00
[2022-12-12 12:49:31,834] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 12:49:32,419] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 12:49:32,480] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 12:49:37,212] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221128T222600, start_date=20221212T124918, end_date=20221212T124937
[2022-12-12 12:49:39,537] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 12:49:41,739] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
