[2022-12-12 12:47:14,010] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T22:20:00+00:00 [queued]>
[2022-12-12 12:47:14,829] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T22:20:00+00:00 [queued]>
[2022-12-12 12:47:14,830] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:47:14,830] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 12:47:14,830] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 12:47:15,947] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-28 22:20:00+00:00
[2022-12-12 12:47:16,288] {standard_task_runner.py:52} INFO - Started process 1121 to run task
[2022-12-12 12:47:16,405] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-11-28T22:20:00+00:00', '--job-id', '360', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpu01o59m5', '--error-file', '/tmp/tmp0sc8w8eb']
[2022-12-12 12:47:16,655] {standard_task_runner.py:80} INFO - Job 360: Subtask create_table
[2022-12-12 12:47:20,174] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-11-28T22:20:00+00:00 [running]> on host b778137d8ea6
[2022-12-12 12:47:25,856] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T22:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T22:20:00+00:00
[2022-12-12 12:47:26,676] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 12:47:27,007] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 12:47:27,019] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 12:47:27,825] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221128T222000, start_date=20221212T124714, end_date=20221212T124727
[2022-12-12 12:47:29,964] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 12:47:34,102] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
