[2022-12-12 13:06:04,449] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T23:35:00+00:00 [queued]>
[2022-12-12 13:06:04,838] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-28T23:35:00+00:00 [queued]>
[2022-12-12 13:06:04,838] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 13:06:04,838] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 13:06:04,838] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 13:06:05,316] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-28 23:35:00+00:00
[2022-12-12 13:06:05,371] {standard_task_runner.py:52} INFO - Started process 1844 to run task
[2022-12-12 13:06:05,476] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-11-28T23:35:00+00:00', '--job-id', '645', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp65mh8emy', '--error-file', '/tmp/tmpeyegkspg']
[2022-12-12 13:06:05,478] {standard_task_runner.py:80} INFO - Job 645: Subtask create_table
[2022-12-12 13:06:06,674] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-11-28T23:35:00+00:00 [running]> on host b778137d8ea6
[2022-12-12 13:06:08,358] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T23:35:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T23:35:00+00:00
[2022-12-12 13:06:08,530] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 13:06:08,593] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 13:06:08,600] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 13:06:08,826] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221128T233500, start_date=20221212T130604, end_date=20221212T130608
[2022-12-12 13:06:09,028] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 13:06:09,929] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
