[2022-12-12 13:14:27,625] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-29T00:12:00+00:00 [queued]>
[2022-12-12 13:14:27,711] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-11-29T00:12:00+00:00 [queued]>
[2022-12-12 13:14:27,711] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 13:14:27,711] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 13:14:27,711] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 13:14:27,798] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-29 00:12:00+00:00
[2022-12-12 13:14:27,806] {standard_task_runner.py:52} INFO - Started process 2197 to run task
[2022-12-12 13:14:27,821] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-11-29T00:12:00+00:00', '--job-id', '788', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp81exr4k2', '--error-file', '/tmp/tmpegrlj8_m']
[2022-12-12 13:14:27,826] {standard_task_runner.py:80} INFO - Job 788: Subtask create_table
[2022-12-12 13:14:28,003] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-11-29T00:12:00+00:00 [running]> on host b778137d8ea6
[2022-12-12 13:14:28,595] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-29T00:12:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-29T00:12:00+00:00
[2022-12-12 13:14:28,738] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 13:14:28,791] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 13:14:28,820] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 13:14:29,258] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221129T001200, start_date=20221212T131427, end_date=20221212T131429
[2022-12-12 13:14:29,487] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 13:14:30,086] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
