[2022-12-12 13:02:45,902] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-12T13:01:00+00:00 [queued]>
[2022-12-12 13:02:46,393] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-12T13:01:00+00:00 [queued]>
[2022-12-12 13:02:46,394] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 13:02:46,394] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 13:02:46,394] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 13:02:46,936] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-12 13:01:00+00:00
[2022-12-12 13:02:47,063] {standard_task_runner.py:52} INFO - Started process 1691 to run task
[2022-12-12 13:02:47,195] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-12T13:01:00+00:00', '--job-id', '583', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmph79a1e8y', '--error-file', '/tmp/tmp83af_q0b']
[2022-12-12 13:02:47,217] {standard_task_runner.py:80} INFO - Job 583: Subtask create_table
[2022-12-12 13:02:49,746] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-12T13:01:00+00:00 [running]> on host b778137d8ea6
[2022-12-12 13:02:52,818] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T13:01:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-12T13:01:00+00:00
[2022-12-12 13:02:53,180] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 13:02:53,326] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-12 13:02:53,375] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-12 13:02:53,842] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221212T130100, start_date=20221212T130245, end_date=20221212T130253
[2022-12-12 13:02:54,293] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 13:02:55,476] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
